name: Deploy to Heroku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Heroku
      uses: akshnz/heroku-login-action@v1.2
      with:
        heroku_api_key: ${{ secrets.HRKU-b32a3477-3def-45ff-af77-23caa503e3fc }}

    - name: Deploy to Heroku
      run: |
        git remote add heroku https://git.heroku.com/credit-scoring-api-yd.git
        git push heroku main
